apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopdemo-dev
spec:
  destination:
    name: ''
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: dev-kustomize
    repoURL: https://github.com/ddz99/shopdemo-config.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
