apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Specify the namespace to install Loki into
namespace: argocd

resources:
  - github.com/grafana/loki/production/helm/loki?ref=v2.9.1

helmCharts:
  - name: loki
    chart: https://grafana.github.io/helm-charts/loki
    version: 5.3.1
    releaseName: loki
    namespace: monitoring
    valuesFile: loki-helm-values.yaml
