replicaCount: 1

loki:
  auth_enabled: false

persistence:
  enabled: true
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  type: NodePort

# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#   hosts:
#     - loki.example.com
