apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      gitlab:
        # The GitLab project ID.
        project: "344"
        api: http://192.168.0.253:9090/
        # Reference to a Secret containing an access token. (optional)
        tokenRef:
          secretName: argo-gitlab
          key: token
        # Labels is used to filter the MRs that you want to target. (optional)
        labels:
        - preview
        # MR state is used to filter MRs only with a certain state. (optional)
        pullRequestState: opened
        # If true, skips validating the SCM provider's TLS certificate - useful for self-signed certificates.
        # insecure: true
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'myapp-{{.branch}}-{{.number}}'
    spec:
      project: academy-demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        path: kustomize/base
        repoURL: 'ssh://git@192.168.0.253:2224/david.duarte/multi-cloud-kubernetes.git'
        targetRevision: '{{.head_sha}}'
      destination:
        name: ''
        namespace: dev-{{.author}}-{{.head_sha}}
        server: 'https://kubernetes.default.svc'
